sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iWbVivkqm3oLrcOqq6bxysgYJljsHdBAVJZXEJ9Ix/CXkw4jf/VoG3yiVbZhKOnNpqbAlpVkhQdWB3krFXtq1feWr6tVGGp02uwed1cBgRCQL6QYRAElOU01n+JyCCskTalhkWS6oLhOCIShMvxMadH7AtOviGiIXWz7pLwxs1QFnwXBp4j9MJshTS91KtZRQRW7EtPu6T9OC4mSPH2D9Y8/xUsZ5Uys7mH+cFICc2myNRBJ74sGHMce81Le/UcIbLMFAosow48Y3Vkf4u4AfTmiwkhQkwjYff2xLIt29t9tjcc5i41QspgUnxAIek0tG8DzY3+3yq5cyv2e+XVQODQ11WSUlJcq5tWTubnWrZkQ8ShwEj7idqWOOKF0vizqu8jR2fwx76/4m1zsWNXjSL0b/uicKBgCTog/mOfpXwiZGN2TG9pWQsofPXFBx3+OBOf1LcxZWXWaJ1KKJR+LETbL5wsJK3iiiCXbZULKydpKhmb4qbdI3BOf2S2AhF4rLf49k1BZ2bKiKzezKswo0U7dKZvJgWHhDwxBrQhYhtPy2tiuwkNLiSkJFka5fdJ5va+MKxTFhJNomXTmLCUYR/xvcbJCmQL9uFMZFz/+zUY7cZFYzzxi+QVkr2bQlI70UwcrydKmQ5kUA+aIZmO84jmawXUQrq8AZHOAkLSG8I4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/History-of-the-United-Netherlands-from-the-Death-of-William-the-Silent-to-the-Twelve-Year-s-Tr__4838
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy